apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ml14-nginx-webpage
spec:
  selector:
    matchLabels:
      app: ml14-nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ml14-nginx
      annotations:
        dummy-for-update: xxxx
    spec:
      containers:
      - name: ml14-nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ml14-persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ml14-persistent-storage
        persistentVolumeClaim:
          claimName: ml14-pv-claim
